for ($i = 1; $i -le 30; $i++) {
  Get-Content Instances/instance05.txt | c:/Users/gabri/Documents/Strip-Packing-Verification-tool-main/.venv/Scripts/python.exe Strip_packing_MKBL_v04.py *> $null
}

## Estatísticas Gerais

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('resumo_alocacao.csv')

df.head()

,Algoritmo,Allocated Pieces,Max Length on Strip,Total Allocation Time (s)
0,MKBL order by area,6,8.0,0.013242
1,MKBL order by area,6,8.0,0.010088
2,MKBL order by area,6,8.0,0.016575
3,MKBL order by area,6,8.0,0.011832
4,MKBL order by area,6,8.0,0.021906

In [3]:
df.describe()

       Allocated Pieces  Max Length on Strip  Total Allocation Time (s)
count              30.0                 30.0                  30.000000
mean                6.0                  8.0                   0.014673
std                 0.0                  0.0                   0.002712
min                 6.0                  8.0                   0.010088
25%                 6.0                  8.0                   0.012880
50%                 6.0                  8.0                   0.013733
75%                 6.0                  8.0                   0.015586
max                 6.0                  8.0                   0.021906

In [4]:
df2 = pd.read_csv('resumo_alocacao2.csv')

df2.head()

,Algoritmo,Allocated Pieces,Max Length on Strip,Total Allocation Time (s)
0,MKBL user choice,0,0.0,0.000486
1,MKBL user choice,0,0.0,0.000471
2,MKBL user choice,0,0.0,0.000662
3,MKBL user choice,0,0.0,0.000748
4,MKBL user choice,0,0.0,0.001180

In [5]:
df2.describe()

       Allocated Pieces  Max Length on Strip  Total Allocation Time (s)
count              30.0                 30.0                  30.000000
mean                0.0                  0.0                   0.000699
std                 0.0                  0.0                   0.000252
min                 0.0                  0.0                   0.000410
25%                 0.0                  0.0                   0.000494
50%                 0.0                  0.0                   0.000653
75%                 0.0                  0.0                   0.000861
max                 0.0                  0.0                   0.001294

In [6]:
# Criar um dataframe do pandas para resumo final, onde tem uma coluna com o tipo de algoritmo, outra com o tempo médio e outra com desvio padrão

df_summary = pd.DataFrame(columns=['Algoritmo', 'Tempo Médio (s)', 'Desvio Padrão (s)'])

# Adicionar os resultados do primeiro algoritmo

# mostrar até 4 casas decimais
mean_time_1 = df['Total Allocation Time (s)'].mean().round(4)
std_dev_time_1 = df['Total Allocation Time (s)'].std().round(4)
    
mean_time_2 = df2['Total Allocation Time (s)'].mean().round(4)
std_dev_time_2 = df2['Total Allocation Time (s)'].std().round(4)

df_summary.loc[len(df_summary)] = ['MKBL order by area', mean_time_1, std_dev_time_1]
df_summary.loc[len(df_summary)] = ['MKBL user choice', mean_time_2, std_dev_time_2]

df_summary.head()

            Algoritmo  Tempo Médio (s)  Desvio Padrão (s)
0  MKBL order by area           0.0147             0.0027
1    MKBL user choice           0.0007             0.0003